### PR TITLE
Create db-init.sh

### PR DESCRIPTION
**Pull request by StaticallyTypedRice**
I thought I'd create a quick script based on [this page in the documentation](https://dev.lemmy.ml/docs/contributing_local_development.html) to speed up initializing the database for slightly more streamlined development and deployment.

### CODE REVIEW

**Comment by dessalines** [comment]
Looks good, could you also add running that script to that doc file? Its in the documentation folder.

**Comment by StaticallyTypedRice** [comment]
> Looks good, could you also add running that script to that doc file? Its in the documentation folder.

Added!

**Comment by StaticallyTypedRice** [comment]
I also implemented database password verification!

**Comment by dessalines** [comment]
Sweet!

**Pull request merged**
