### PR TITLE
Add a HTTP API

### LINKED ISSUE #380: Expose API over HTTP
Right now the API is only available over websocket. It would be very useful if it was also available via HTTP as a REST API. Preferably without duplicating all the existing API code.

[See this document for an overview of the existing websocket API](https://github.com/dessalines/lemmy/blob/master/docs/api.md)

### LINKED ISSUE #437: Generate documentation for HTTP API
Would be cool if this could somehow be generated automatically. Here is some discussion about it.

https://github.com/fafhrd91/actix-web/issues/310

### PR DESCRIPTION
**Pull request by dessalines**
Fixes #380 
Fixes #437

### CODE REVIEW

**Comment by Nutomic** [comment]
Please squash the commits before merging ;)

**Comment by Nutomic** [comment]
What's missing to merge this?

**Comment by dessalines** [comment]
@Nutomic I put some notes at the bottom here: https://yerbamate.dev/dessalines/lemmy/pulls/14

Do those, then I'll worry about the conflicts. I have a big merge to do with this private messaging anyway.

**Comment by dessalines** [comment]
This got merged in to dev, and is in master in https://github.com/dessalines/lemmy/commit/c3eaa2273a24093b5d2c78bcb3610a76a6d722c6

**Pull request closed without merging**
