### PR TITLE
Clarify that content violating this code of conduct will likely be removed.

### PR DESCRIPTION
**Pull request by StaticallyTypedRice**
Lemmy has a general policy of removing any content that violates the rules whenever possible, which is typically a good thing, and I felt it important to mention that in the code of conduct.

### CODE REVIEW

**Comment by dessalines** [comment]
Sweet, thanks.

**Comment by Nutomic** [comment]
I would think that this is obvious, but can't hurt to mention it. Though I would say that anything violating the coc will *definitely* be removed.

**Comment by StaticallyTypedRice** [comment]
> Though I would say that anything violating the coc will definitely be removed.

In that case should we take out the "whenever possible" part?

**Comment by Nutomic** [comment]
Yes I think so, because I dont see any reason why it wouldnt be possible to remove such things (the coc only applies to stuff that we have control over).

**Comment by StaticallyTypedRice** [comment]
Should I make another PR with the change since this one is closed already?

**Pull request merged**
