### PR TITLE
Adding icons.

### LINKED ISSUE #573: Try out icons for actions.
- [x] Look at twidere, slide, and twitter for how the actions look.
- [x] html `title` attribute is useless on mobile, so use tippyjs with a delay for describing. Grep for title in tsx files.

- [How to set up long-press with tippyjs](https://github.com/atomiks/tippyjs/issues/522)

### PR DESCRIPTION
**Pull request by dessalines**
Fixes #573

### CODE REVIEW

**Comment by Nutomic** [comment]
They look good, just maybe a bit tiny.

**Comment by dessalines** [comment]
I'll see what they look like a little bigger.

**Comment by Nutomic** [comment]
Actually on mobile its pretty bad, it was already hard to press the small text before, but now its basically impossible unless you concentrate a lot, that sucks.

**Comment by Nutomic** [comment]
And its not clear what the icons mean. Probably better to put icon and text both (and much bigger like Android apps do it).

**Comment by dessalines** [comment]
I've just tested it out a bunch on mobile, its really nice. I added a library specifically so you can click and hold on buttons if you're not sure what they do. I'm basing this off of how several android apps look.

**Pull request merged**
