### PR TITLE
Add additional features to the README.

### PR DESCRIPTION
**Pull request by StaticallyTypedRice**

### CODE REVIEW

**Comment by Nutomic** [comment]
Should we really add so many details? The list is already too long to read imo.

**Comment by dessalines** [comment]
I'm with @Nutomic here, the list is probably too long as it currently is. If I gave everything I've worked on w/ lemmy in the past year, it would be a book.

The only thing I see added here that isn't there already, is private messaging.

@StaticallyTypedRice Also in the future, please do PRs from new branches based off master, most of those commits aren't doing anything.

**Comment by StaticallyTypedRice** [comment]
I will remove some of the less significant features and try to boil it down to the essentials.

**Comment by StaticallyTypedRice** [comment]
Updated. How's it now?

**Comment by dessalines** [comment]
I'm just gonna close this, because it still has all the other unnecessary commits, and the only line I liked that you added was ` - Direct messaging support. `, which I'll just do now.

**Pull request closed without merging**
