### PR TITLE
add russian translation

### PR DESCRIPTION
**Pull request by korolr**

### CODE REVIEW

**Comment by dessalines** [comment]
@digitalkiller already added one, lol. But once I merge it here in a minute you could go over and make sure its good.

**Comment by dessalines** [comment]
[Here's the one they made BTW](https://github.com/dessalines/lemmy/blob/master/ui/src/translations/ru.ts), you could go over it and make sure it's good if you like.

**Comment by korolr** [comment]
lol

**Comment by digitalkiller** [comment]
lol

**Pull request closed without merging**
