### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BoFFire**
Adding translation widget %

### CODE REVIEW

**Comment by Nutomic** [comment]
I'm not a fan of these badges, but if we put it then at least remove the `?utm_source=widget` from the link, no one needs that tracking.

**Comment by BoFFire** [comment]
Copied from here : https://weblate.yerbamate.dev/widgets/lemmy/?lang=&component=lemmy

**Comment by Nutomic** [comment]
Right, but you can just remove the part after `?` from the link and it will still work. Or generally anything like `?utm_*` or `&utm_*`.

**Comment by Nutomic** [comment]
https://en.wikipedia.org/wiki/UTM_parameters

**Comment by BoFFire** [comment]
Can you correct it for me ^-^ I don't have a computer. I opened the PR with my phone.

**Comment by Nutomic** [comment]
Oh I didnt even know that I can edit other people's PRs through the website. Pretty cool.

Thanks for the PR, and for all your help with weblate :)

**Comment by BoFFire** [comment]
Thank you @Nutomic, I appreciate :)

**Comment by dessalines** [comment]
Just tested it, looks great. Thanks yall.

**Pull request merged**
